/* Question: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibionacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

//solution:
//start:
function fibioncciSum(){
	var array= [1,2]
	var newArray =[];
	var sumOfArray=0;

	var condition=0;
    while(condition<4000000){
    	array.push(array[array.length-1]+array[array.length-2]);
        condition = array[array.length-1]+array[array.length-2]
    }
    console.log(array);
     
    for (var i in array){
    	if(array[i]%2===0){
    		newArray.push(array[i]);
   
    	}
    }
    console.log(newArray);
    for (var i in newArray){
    	sumOfArray += newArray[i];
    }



    return sumOfArray;
	}

//end
